Frontend:
  impl: GEM5
  clock_ratio: 1
  num_expected_insts: 500000
  llc_capacity_per_core: 2MB

Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    RFM:
      BRC: 4
    impl: HBM3
    org:
      preset: HBM3_2Gb
      channel: 16
      rank: 1
    timing:
      preset: HBM3_2Gbps

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh